name: Publish Plugin to Marketplace

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - run: yarn install

    - name: Vscode release plugin
      uses: JCofman/vscodeaction@1.0.0
      env:
        PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
      with:
        args: publish -p $PUBLISHER_TOKEN
